# Generated by Django 3.2 on 2023-06-22 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория произведения', 'verbose_name_plural': 'Категории произведений'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'Жанр произведения', 'verbose_name_plural': 'Жанры произведений'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-year',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='name', max_length=256, verbose_name='Название категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='slug', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$')], verbose_name='Слаг категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='name', max_length=256, verbose_name='Название жанра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.CharField(default='slug', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$')], verbose_name='Слаг жанра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title', to='titles.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='title', to='titles.Genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default='a', max_length=256, verbose_name='Название произведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
