# Generated by Django 3.2 on 2023-06-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20230614_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
