# Generated by Django 3.2 on 2023-06-15 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_auto_20230615_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='a', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.CharField(default='b', max_length=50, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$')]),
            preserve_default=False,
        ),
    ]
