# Generated by Django 3.2 on 2023-06-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0010_auto_20230615_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория произведения', 'verbose_name_plural': 'Категории произведений'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'Жанр произведения', 'verbose_name_plural': 'Жанры произведений'},
        ),
    ]
